using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BackEnd.Enum
{
    public enum EnumErrores
    {
        excepcionBaseDatos = -2,
        excepcionLogica = -1,
        requestNulo = 1,
        nombreFaltante = 2,
        apellidoFaltante = 3,
        correoFaltante = 4,
        passwordFaltante = 5,
        correoIncorrecto = 6,
        passwordMuyDebil = 7,
        idFaltante = 8,
        sesionCerrada = 9,
        verificacionFallida = 10,
        verificacionExpirada = 11,
        usuarioFaltante = 12,
        gimnasioFaltante = 13,
        rolFaltante = 14,
        telefonoFaltante = 15,
        fechaFaltante = 16,
        membresiaFaltante = 17,
        pagoFaltante = 18,
        montoInvalido = 19,
        metodoPagoInvalido = 20,
        membresiaVencida = 21,
        membresiaInexistente = 22,
        usuarioInactivo = 23,
        rutinaDuplicada = 24,
        ejercicioFaltante = 25,
        datosIncompletos = 26,
        entidadNoEncontrada = 27,
        tipoRutinaInvalido = 28,
        estadoPagoInvalido = 29,
        asistenciaNoRegistrada = 30,
        usuarioSuspendido = 31,
        credencialesInvalidas = 32,
        sesionExpirada = 33,
        permisoInsuficiente = 34,
        operacionNoPermitida = 35,
        logroNoEncontrado = 36,
        metaInvalida = 37,
        desafioDuplicado = 38,
        desafioNoActivo = 39,
        yaParticipando = 40,
        valorFueraDeRango = 41,
        fechaInvalida = 42,
        datosDuplicados = 43,
        direccionFaltante = 44,
        horarioInvalido = 45,
        duracionInvalida = 46,
        usuarioNoEncontrado = 47,
        cedulaFaltante = 48,
        errorDesconocido = 49,
        periodoFaltante = 50,
        periodoInvalido = 51,
        gimnasioNoEncontrado = 52,
        reporteNoGenerado = 53,
        datosFaltantes = 54,
        fechaFinMenorQueInicio = 55,
        reporteNoEncontrado = 56,
        metodoRegistroFaltante = 57,
        gimnasioInvalido = 58,
        fechasInvalidas = 59,
        tipoEstadisticaInvalido = 60,
        sesionNula = 101,
        sesionNoEncontrada = 102,
        passwordIncorrecto = 103,
        pagasinMembresias = 104,
        tipoMembresiaInvalido = 105,
        montoIncompatible = 106,
        metodoPagoNoDisponible = 107,
        pagoYaProcesado = 108,
        membresiaYaActiva = 109,
        sinMembresiaActiva = 110,
        administradorRequerido = 111,
        tokenAdminRequerido = 112
    }
}
